#!/bin/sh

server="$1"
to="$2"
if [ -z "$to" ]; then
	exit 1
fi

subject="No subject"
while read -r field rest; do
	case "$field" in
		"") break ;;
		Subject:) subject="$rest" ;;
	esac
done
case "$subject" in
	*"'"*) subject="No subject"
esac
ssh "$server" mail -s "'$subject'" "$to"
